#!/usr/bin/env python
import os
from tqdm import tqdm

# wrap everything in a tqdm progress bar so I can see overall progress of the script
with tqdm(total=100, desc="Overall Progress") as pbar:
    os.system("figlet -f slant 'skullzarmy'")
    print("Welcome to skullzarmy's Kali setup script!")
    print("This script will install the following tools:")
    print("  - gitleaks")
    print("  - VS Code")
    print("  - VS Code extensions")
    print("  - VS Code themes")
    print("  - openai for python")
    os.system("figlet -f slant '|||||||||||||||||||||||||||'")
    pbar.update(10)

    print("==================================")
    print("Update apt")
    print("==================================")
    os.system("sudo apt update")
    pbar.update(10)
    print("==================================")
    print("Install gitleaks")
    print("==================================")
    os.system("sudo apt install gitleaks")
    pbar.update(10)
    print("==================================")
    print("Install latest version of VS Code")
    print("==================================")
    print("if microsoft.gpg does not exists on disk")
    if not os.path.exists("microsoft.gpg"):
        os.system("curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg")
        os.system("sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/")
        os.system("sudo sh -c 'echo \"deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main\" > /etc/apt/sources.list.d/vscode.list'")
    os.system("sudo apt update")
    os.system("sudo apt install code")
    pbar.update(30)
    print("==================================")
    print("Install VS Code extensions")
    print("==================================")
    os.system("code --install-extension akamud.vscode-theme-onedark")
    os.system("code --install-extension formulahendry.auto-rename-tag")
    os.system("code --install-extension ms-azuretools.vscode-docker")
    os.system("code --install-extension github.copilot")
    os.system("code --install-extension davidanson.vscode-markdownlint")
    os.system("code --install-extension ms-python.python")
    os.system("code --install-extension chakrounAnas.turbo-console-log")
    pbar.update(30)
    print("==================================")
    print("Install OpenAI library")
    print("==================================")
    os.system("sudo pip install openai")
    pbar.update(10)
    print("==================================")
pbar.close()

os.system("figlet -f slant 'DONE'")
print("Happy hunting!")
